# Code Review Workflow for Backend (Python/FastAPI)
# Uses OpenAI GPT-4 for code review with A/B risk classification
#
# Migration from Claude to OpenAI: Required OPENAI_API_KEY secret.
# This is a permanent migration to use OpenAI's GPT-4o model.

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
      - '**.sql'
      - 'requirements*.txt'
      - 'pyproject.toml'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  risk-scan:
    name: Risk Classification Scan
    runs-on: ubuntu-latest
    outputs:
      has_a_class_risks: ${{ steps.parse.outputs.has_a_class_risks }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.py
            **/*.sql

      - name: Get PR diff
        id: diff
        run: |
          # Handle file names with special characters safely
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | xargs -I {} git diff ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} -- "{}" > pr_diff.txt || true

          DIFF_SIZE=$(wc -c < pr_diff.txt)
          echo "Diff size: $DIFF_SIZE bytes"

          # Check for empty diff
          if [ ! -s pr_diff.txt ]; then
            echo "No relevant files changed, skipping AI review"
            echo '{"has_a_class_risks": false, "total_a_class": 0, "total_b_class": 0}' > review_result.txt
            echo "skip_review=true" >> $GITHUB_OUTPUT
          else
            echo "skip_review=false" >> $GITHUB_OUTPUT
            # Warn if diff was truncated
            if [ "$DIFF_SIZE" -gt 50000 ]; then
              echo "::warning::Diff truncated from $DIFF_SIZE to 50000 bytes"
            fi
          fi

      - name: Fetch review rules
        if: steps.diff.outputs.skip_review != 'true'
        run: |
          mkdir -p .review-rules
          curl -sfL https://raw.githubusercontent.com/YoumigoTech/code-review-agent/main/rules/a-class-risks.md -o .review-rules/a-class-risks.md || { echo "::error::Failed to fetch a-class-risks.md"; exit 1; }
          curl -sfL https://raw.githubusercontent.com/YoumigoTech/code-review-agent/main/rules/b-class-risks.md -o .review-rules/b-class-risks.md || { echo "::error::Failed to fetch b-class-risks.md"; exit 1; }
          curl -sfL https://raw.githubusercontent.com/YoumigoTech/code-review-agent/main/rules/python-patterns.md -o .review-rules/python-patterns.md || { echo "::error::Failed to fetch python-patterns.md"; exit 1; }

      - name: Run AI Code Review
        id: scan
        if: steps.diff.outputs.skip_review != 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Check API key exists
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "::error::OPENAI_API_KEY secret is not configured"
            exit 1
          fi

          A_CLASS_RULES=$(cat .review-rules/a-class-risks.md)
          B_CLASS_RULES=$(cat .review-rules/b-class-risks.md)
          PYTHON_PATTERNS=$(cat .review-rules/python-patterns.md)
          PR_DIFF=$(cat pr_diff.txt | head -c 50000)

          # Create prompt file to avoid shell escaping issues
          cat > prompt.txt << 'PROMPT_END'
          You are a code review agent. Analyze the following PR diff and classify risks.

          ## Risk Classification Rules

          ### A-Class Risks (BLOCKING - require human approval)
          PROMPT_END
          echo "$A_CLASS_RULES" >> prompt.txt
          cat >> prompt.txt << 'PROMPT_END'

          ### B-Class Risks (NON-BLOCKING - suggestions only)
          PROMPT_END
          echo "$B_CLASS_RULES" >> prompt.txt
          cat >> prompt.txt << 'PROMPT_END'

          ### Python-Specific Patterns
          PROMPT_END
          echo "$PYTHON_PATTERNS" >> prompt.txt
          cat >> prompt.txt << 'PROMPT_END'

          ## PR Diff
          ```diff
          PROMPT_END
          echo "$PR_DIFF" >> prompt.txt
          cat >> prompt.txt << 'PROMPT_END'
          ```

          ## Instructions

          1. Analyze the diff for A-class and B-class risks
          2. For each risk found, output in this format:

          ### A-Class Risks Found
          ```
          RISK_LEVEL: A
          FILE: <filepath>
          LINE: <line_number>
          TYPE: <A1-A6>
          DESCRIPTION: <description>
          RECOMMENDATION: <how to fix>
          ```

          ### B-Class Risks Found
          ```
          RISK_LEVEL: B
          FILE: <filepath>
          LINE: <line_number>
          TYPE: <B1-B6>
          DESCRIPTION: <description>
          SUGGESTION: <corrected code>
          ```

          ### Summary
          ```json
          {"has_a_class_risks": true|false, "total_a_class": <count>, "total_b_class": <count>}
          ```

          Be thorough but avoid false positives. Only flag genuine risks.
          PROMPT_END

          # Call OpenAI API
          PROMPT_CONTENT=$(cat prompt.txt)
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "$(jq -n --arg prompt "$PROMPT_CONTENT" '{
              model: "gpt-4o",
              messages: [{"role": "user", "content": $prompt}],
              max_tokens: 4000,
              temperature: 0.1
            }')")

          # Extract response
          REVIEW_RESULT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // empty')

          # Check for API errors - fail workflow if review failed
          if [ -z "$REVIEW_RESULT" ]; then
            ERROR_MSG=$(echo "$RESPONSE" | jq -r '.error.message // "Unknown error"')
            echo "::error::OpenAI API error: $ERROR_MSG"
            echo "Error calling OpenAI API: $ERROR_MSG" > review_result.txt
            exit 1
          fi

          echo "$REVIEW_RESULT" > review_result.txt

      - name: Parse scan results
        id: parse
        run: |
          if grep -q '"has_a_class_risks": true\|"has_a_class_risks":true' review_result.txt; then
            echo "has_a_class_risks=true" >> $GITHUB_OUTPUT
          else
            echo "has_a_class_risks=false" >> $GITHUB_OUTPUT
          fi

      - name: Post review comments
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const response = fs.readFileSync('review_result.txt', 'utf8') || 'No response from AI review';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## AI Code Review Results (GPT-4)\n\n${response}`
            });

  block-on-a-class:
    name: A-Class Risk Gate
    runs-on: ubuntu-latest
    needs: risk-scan
    if: needs.risk-scan.outputs.has_a_class_risks == 'true'
    steps:
      - name: Block PR
        run: |
          echo "::error::A-Class risks detected. Human review required."
          echo ""
          echo "This PR contains A-Class risks that require human review."
          echo "Please review the AI Code Review comment and either:"
          echo "  1. Fix the identified risks"
          echo "  2. Add RISK-ACCEPTED comments with justification"
          echo "  3. Request exemption from a senior engineer"
          exit 1

  approve-no-risks:
    name: No A-Class Risks
    runs-on: ubuntu-latest
    needs: risk-scan
    if: needs.risk-scan.outputs.has_a_class_risks == 'false'
    steps:
      - name: Approve
        run: |
          echo "No A-Class risks detected. PR can proceed."
          echo "Please review any B-Class suggestions in the PR comments."
