# Code Review Workflow for Infrastructure (TypeScript/CDK)
# Uses OpenAI GPT-4 for code review with A/B risk classification

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.yaml'
      - '**.yml'
      - 'cdk.json'
      - 'package*.json'
      - 'tsconfig*.json'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  risk-scan:
    name: Risk Classification Scan
    runs-on: ubuntu-latest
    outputs:
      has_a_class_risks: ${{ steps.parse.outputs.has_a_class_risks }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.ts
            **/*.tsx
            **/*.yaml
            **/*.yml

      - name: Get PR diff
        run: |
          git diff ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} -- ${{ steps.changed-files.outputs.all_changed_files }} > pr_diff.txt
          echo "Diff size: $(wc -c < pr_diff.txt) bytes"

      - name: Fetch review rules
        run: |
          mkdir -p .review-rules
          curl -sfL https://raw.githubusercontent.com/YoumigoTech/code-review-agent/main/rules/a-class-risks.md -o .review-rules/a-class-risks.md || { echo "::error::Failed to fetch a-class-risks.md"; exit 1; }
          curl -sfL https://raw.githubusercontent.com/YoumigoTech/code-review-agent/main/rules/b-class-risks.md -o .review-rules/b-class-risks.md || { echo "::error::Failed to fetch b-class-risks.md"; exit 1; }
          curl -sfL https://raw.githubusercontent.com/YoumigoTech/code-review-agent/main/rules/cdk-patterns.md -o .review-rules/cdk-patterns.md || { echo "::error::Failed to fetch cdk-patterns.md"; exit 1; }

      - name: Run AI Code Review
        id: scan
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          A_CLASS_RULES=$(cat .review-rules/a-class-risks.md)
          B_CLASS_RULES=$(cat .review-rules/b-class-risks.md)
          CDK_PATTERNS=$(cat .review-rules/cdk-patterns.md)
          PR_DIFF=$(cat pr_diff.txt | head -c 50000)

          cat > prompt.txt << 'PROMPT_END'
          You are a code review agent for AWS CDK/TypeScript infrastructure. Analyze the PR diff and classify risks.

          ## Risk Classification Rules

          ### A-Class Risks (BLOCKING - require human approval)
          PROMPT_END
          echo "$A_CLASS_RULES" >> prompt.txt
          cat >> prompt.txt << 'PROMPT_END'

          ### B-Class Risks (NON-BLOCKING - suggestions only)
          PROMPT_END
          echo "$B_CLASS_RULES" >> prompt.txt
          cat >> prompt.txt << 'PROMPT_END'

          ### CDK/TypeScript-Specific Patterns
          PROMPT_END
          echo "$CDK_PATTERNS" >> prompt.txt
          cat >> prompt.txt << 'PROMPT_END'

          ## Infrastructure-Specific Checks
          Pay special attention to:
          - Hardcoded AWS account IDs or regions - A1 risk
          - Missing RemovalPolicy on stateful resources - A5 risk
          - Overly permissive IAM policies (`*` actions or resources) - A1 risk
          - Secrets in plain text - A1 risk (CRITICAL)
          - Non-null assertions (`!`) - A1 risk
          - `any` type usage - A1 risk

          ## PR Diff
          ```diff
          PROMPT_END
          echo "$PR_DIFF" >> prompt.txt
          cat >> prompt.txt << 'PROMPT_END'
          ```

          ## Instructions
          1. Analyze the diff for A-class and B-class risks
          2. Output format:

          ### A-Class Risks Found
          ```
          RISK_LEVEL: A
          FILE: <filepath>
          LINE: <line_number>
          TYPE: <A1-A6>
          DESCRIPTION: <description>
          RECOMMENDATION: <how to fix>
          ```

          ### B-Class Risks Found
          ```
          RISK_LEVEL: B
          FILE: <filepath>
          LINE: <line_number>
          TYPE: <B1-B6>
          DESCRIPTION: <description>
          SUGGESTION: <corrected code>
          ```

          ### Summary
          ```json
          {"has_a_class_risks": true|false, "total_a_class": <count>, "total_b_class": <count>}
          ```

          Be especially strict about IAM policies and secret handling.
          PROMPT_END

          PROMPT_CONTENT=$(cat prompt.txt)
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "$(jq -n --arg prompt "$PROMPT_CONTENT" '{
              model: "gpt-4o",
              messages: [{"role": "user", "content": $prompt}],
              max_tokens: 4000,
              temperature: 0.1
            }')")

          REVIEW_RESULT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // empty')

          if [ -z "$REVIEW_RESULT" ]; then
            ERROR_MSG=$(echo "$RESPONSE" | jq -r '.error.message // "Unknown error"')
            echo "::error::OpenAI API error: $ERROR_MSG"
            REVIEW_RESULT="Error calling OpenAI API: $ERROR_MSG"
          fi

          echo "$REVIEW_RESULT" > review_result.txt

      - name: Parse scan results
        id: parse
        run: |
          if grep -q '"has_a_class_risks": true\|"has_a_class_risks":true' review_result.txt; then
            echo "has_a_class_risks=true" >> $GITHUB_OUTPUT
          else
            echo "has_a_class_risks=false" >> $GITHUB_OUTPUT
          fi

      - name: Post review comments
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const response = fs.readFileSync('review_result.txt', 'utf8') || 'No response from AI review';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## AI Code Review Results (Infrastructure/CDK - GPT-4)\n\n${response}`
            });

  block-on-a-class:
    name: A-Class Risk Gate
    runs-on: ubuntu-latest
    needs: risk-scan
    if: needs.risk-scan.outputs.has_a_class_risks == 'true'
    steps:
      - name: Block PR
        run: |
          echo "::error::A-Class risks detected in infrastructure code. Human review required."
          exit 1

  approve-no-risks:
    name: No A-Class Risks
    runs-on: ubuntu-latest
    needs: risk-scan
    if: needs.risk-scan.outputs.has_a_class_risks == 'false'
    steps:
      - name: Approve
        run: echo "No A-Class risks detected. PR can proceed."
